// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TrillXPF
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class EventRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""EventRecord"",""namespace"":""TrillXPF"",""fields"":[{""name"":""DeviceID"",""type"":""int""},{""name"":""Timestamp"",""type"":""long""},{""name"":""EventID"",""type"":""int""},{""name"":""EventData"",""type"":{""type"":""record"",""name"":""EventDataRecord"",""namespace"":""TrillXPF"",""fields"":[{""name"":""Latitude"",""type"":""float""},{""name"":""Longitude"",""type"":""float""},{""name"":""Accuracy"",""type"":""int""}]}}]}");
		private int _DeviceID;
		private long _Timestamp;
		private int _EventID;
		private TrillXPF.EventDataRecord _EventData;
		public virtual Schema Schema
		{
			get
			{
				return EventRecord._SCHEMA;
			}
		}
		public int DeviceID
		{
			get
			{
				return this._DeviceID;
			}
			set
			{
				this._DeviceID = value;
			}
		}
		public long Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				this._Timestamp = value;
			}
		}
		public int EventID
		{
			get
			{
				return this._EventID;
			}
			set
			{
				this._EventID = value;
			}
		}
		public TrillXPF.EventDataRecord EventData
		{
			get
			{
				return this._EventData;
			}
			set
			{
				this._EventData = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DeviceID;
			case 1: return this.Timestamp;
			case 2: return this.EventID;
			case 3: return this.EventData;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DeviceID = (System.Int32)fieldValue; break;
			case 1: this.Timestamp = (System.Int64)fieldValue; break;
			case 2: this.EventID = (System.Int32)fieldValue; break;
			case 3: this.EventData = (TrillXPF.EventDataRecord)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
