// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TrillXPF
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class EventDataRecord : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"EventDataRecord\",\"namespace\":\"TrillXPF\",\"fields\":[{\"name" +
				"\":\"Latitude\",\"type\":\"float\"},{\"name\":\"Longitude\",\"type\":\"float\"},{\"name\":\"Accura" +
				"cy\",\"type\":\"int\"}]}");
		private float _Latitude;
		private float _Longitude;
		private int _Accuracy;
		public virtual Schema Schema
		{
			get
			{
				return EventDataRecord._SCHEMA;
			}
		}
		public float Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				this._Latitude = value;
			}
		}
		public float Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				this._Longitude = value;
			}
		}
		public int Accuracy
		{
			get
			{
				return this._Accuracy;
			}
			set
			{
				this._Accuracy = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Latitude;
			case 1: return this.Longitude;
			case 2: return this.Accuracy;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Latitude = (System.Single)fieldValue; break;
			case 1: this.Longitude = (System.Single)fieldValue; break;
			case 2: this.Accuracy = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
